version: "3.8"

services:
  postgres:
    image: library/postgres:13
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"

  cars:
    build: ./v3/cars
    container_name: cars
    restart: on-failure
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/cars
    ports:
      - "8070:8070"
    depends_on:
      - postgres

  rentals:
    build: ./v3/rentals
    container_name: rentals
    restart: on-failure
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/rentals
    ports:
      - "8060:8060"
    depends_on:
      - postgres

  payments:
    build: ./v3/payments
    container_name: payments
    restart: on-failure
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/payments
    ports:
      - "8050:8050"
    depends_on:
      - postgres

  gateway:
    build: ./v3/gateway
    container_name: gateway
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - cars
      - rentals
      - payments

volumes:
  db-data:
